[project]
name = "sensibull-tracker"
version = "0.1.0"
description = "Sensibull Position Tracker"
requires-python = ">=3.9,<3.14"
dependencies = [
    "flask",
    "flask-login",
    "requests",
    "apscheduler",
    "simplejson",
]
